### ISSUE TITLE
Choker of Enlightenment

### ISSUE THREAD

**Issue by Franzz** [Nostralia/Bugtracker#1]
In PTR the bonus is -25mana on all spells:
![image](https://user-images.githubusercontent.com/298765/30105371-7cf2f4b4-934c-11e7-8afe-648821d8cdbb.png)

But on webarchive, the bonus was still +18 spell and healing damage on 26.12.2005 (> 13.09.2005, Patch 1.7 release date):

https://web-beta.archive.org/web/20051226014816/http://wow.allakhazam.com:80/db/item.html?witem=17109

**Comment by Franzz** [comment]
actually 26.12.2005 is also > 10.10.2005 which is the release date of 1.8. no way of knowing which patch switch the -25mana to the +18 damage.

It doesn't seem to be in neither 1.7 to 1.8 progression file ( https://github.com/elysium-project/database/blob/master/progression/1.7%20%E2%86%92%201.8%20Dragons%20of%20Nightmare.sql ) nor 1.6 to 1.7 ( https://github.com/elysium-project/database/blob/master/progression/1.6%20%E2%86%92%201.7%20Rise%20of%20the%20Blood%20God.sql ).

But one thing is for sure, pre patch 1.6, it was +18 damage (09.09.2005): 

https://web-beta.archive.org/web/20050909010557/http://wow.allakhazam.com:80/db/item.html?witem=17109

**Comment by ruscur** [comment]
I think the safe thing to do here would be to leave it in its "final" state as is now in 1.12 - it changes the purpose of the item, and if it's only going to be a month or so anyway, easier to leave it as-is since we're unsure

**Comment by ruscur** [comment]
this was fixed last week
