### ISSUE TITLE
1.7 Collection of Hakkar bugs (ZG)

### ISSUE THREAD

**Issue by deancornish** [Nostralia/Bugtracker#13]
1. The edge platforms at the top at the bottom of the stairs are incorrectly set for LOS- if you go too far to the edge, you'll aggro the Gurubashi Berserkers downstairs

1. The Platform directly in front of Hakkar was a safe zone in retail, however on our server, he will automatically target and initiate combat with anyone standing on that platform. (this may not be an actual bug, it may be 3) below, and the platform doesnt matter. Raising it just in case).

1. When the boss resets, and spawns in- he remembers who had the highest aggro on him before the reset, and will immediately initiate combat and attack them.

1. When tanks are MC's, they are often sheeped, when they are sheeped they drop aggro and go out of combat, wiping out their aggro and essentially assuring its a wipe.

**Comment by ruscur** [comment]
5. Hakkar does not persist in the instance from night to night within the same lockout - i.e. he is summoned on one night, not killed, and then is not present and unsummonable on the following night.

**Comment by ruscur** [comment]
6. Hakkar sometimes mind controls two tanks at a time instead of just one

7. Mind Control sometimes lasts 20 seconds instead of its regular duration

**Comment by ghost** [comment]
1. invalid/wontfix
2. fixed
3. need to check if still buggy
4. fixed
5. should be fixed
6. fixed
7. need to check if still buggy
