### ISSUE TITLE
Sapphiron Drape

### ISSUE THREAD

**Issue by Franzz** [Nostralia/Bugtracker#3]
In game:  +7 damage
![image](https://user-images.githubusercontent.com/298765/30106590-0a0279a8-9350-11e7-9f8e-2669089a683e.png)

Web archive on 06.09.2005 (patch 1.5): +14 damage
https://web-beta.archive.org/web/20050906021140/http://wow.allakhazam.com:80/db/item.html?witem=17078

Web archive on 30.11.2005 (patch 1.8): +14 damage
https://web-beta.archive.org/web/20051130202332/http://wow.allakhazam.com:80/db/item.html?witem=17078

**Comment by ruscur** [comment]
fixed
