### ISSUE TITLE
STV Fishing Event

### ISSUE THREAD

**Issue by Ehvyn** [Nostralia/Bugtracker#31]
Summary - STV Fishing Event is meant to begin at 2pm Server Time. At this time, schools of Speckled Tastyfish should occur in STV for players to fish from. NPC's in capital cities advised players of this also. As of 2:10pm, there was no NPC in Booty Bay to hand these in to, nor was there any pools of fish for players to fish from. Despite the lack of pools, players were still able to fish these up (which they should not have been able to) at the water around ZG Island.
Reported by: Cicconeyouth, Otago, Lockator, Ehvyn

**Comment by Ehvyn** [comment]
It seems the time is out for the event. At 1am on a Monday, the pools are up and the NPC is there.

**Comment by Sinqnew-Nostralia** [comment]
If GMs could be given .event start command we can manually start the two aspects of the event that don't auto-start.
However, if we could automate this, that'd be better.

**Comment by PeytonNostralia** [comment]
It started at 00:00 tonight Monday 30th October 2017 server time. Pools just appeared. Players spotted fishing!
Server time is incorrect as well in comparison to local times.

**Comment by ghost** [comment]
Should now start on sundays at 2p.m. until 5p.m.
