### ISSUE TITLE
Hunter weapon damage is normalized

### ISSUE THREAD

**Issue by Exarch0** [Nostralia/Bugtracker#39]
Hunter weapon damage (aimed shot and multi-shot) was normalized in patch 1.10 (http://wowwiki.wikia.com/wiki/Patch_1.10).

In the current patch, 1.7,  these abilities should be using the weapon speed as the multiplier rather than the 'normalized' 2.8.

The current call chain for Multi-Shot and Aimed Shot is:

Spell::EffectWeaponDmg:
     case SPELL_EFFECT_NORMALIZED_WEAPON_DMG:
                fixed_bonus += CalculateDamage(SpellEffectIndex(j), unitTarget);
                **normalized = true;**
                break;
-> Unit::CalculateDamage(normalized=TRUE)
-> Player::CalculateMinMaxDamage
-> Unit::GetAPMultiplier

**Comment by Exarch0** [comment]
Forgot the other reference:

The CalculateDamage directly before setting normalized = true leads to Unit::MeleeDamageBonusDone, with the 'weapon damage based spells' subsection containing
```
bool normalized = spellProto ? IsSpellHaveEffect(spellProto, SPELL_EFFECT_NORMALIZED_WEAPON_DMG) : false;
        DoneTotal += int32(APbonus / 14.0f * GetAPMultiplier(attType, normalized));
```

**Comment by ghost** [comment]
Very usefull report, but we don't change character spells for specific patches
