### ISSUE TITLE
Songstone of Ironforge

### ISSUE THREAD

**Issue by Franzz** [Nostralia/Bugtracker#4]
In game: +9 damage
![image](https://user-images.githubusercontent.com/298765/30107327-854be50c-9352-11e7-8d84-01c7d86133de.png)

04.04.2005: +10 damage
https://web-beta.archive.org/web/20050404092007/http://wow.allakhazam.com:80/db/item.html?witem=12543

22.06.2006: +18 damage
https://web-beta.archive.org/web/20060228064824/http://wow.allakhazam.com:80/db/item.html?witem=12543

**Comment by ruscur** [comment]
Second source is patch 1.9, correct value is probably +10

**Comment by ruscur** [comment]
fixed; it's +18 in this patch after all
