### ISSUE TITLE
Garosh the Dervish - Loot

### ISSUE THREAD

**Issue by Sinqnew-Nostralia** [Nostralia/Bugtracker#41]
Garosh the Dervish is dropping no items whatsoever from his loot table apart from some silver and runecloth.

Should drop at least one of the blue/epic items from his table at minimum.

A while back he dropped nothing because of an issue between itemisation and loot tables. The items he was meant to drop had been reitemised to AQ levels so they had to be removed from his loot table. Now that things are itemised properly (I think) he should have a correct loot table again which includes other savage glad gear

**Comment by Ethugd** [comment]
do you have any proof? this is so wrong, the other savage gladiator pieces drop from the other bosses. he drops nothing till except the chest piece till 1.10

**Comment by ruscur** [comment]
yeah he has an interesting loot table.  he has 20% to drop gear at all, and within that a loot table where savage gladiator chain is the only patch appropriate item (15% within that loot table).

this is his actual loot table at present:

http://vanillawowdb.com/?npc=9027

which as far as I know is blizzlike.
