### ISSUE TITLE
MC Pattern Droprates bugged

### ISSUE THREAD

**Issue by rinzip** [Nostralia/Bugtracker#42]
Assuming we are using the same droprates as Elysium/LH, the MC patterns are currently about 1/10th the droprate they should be. Going from http://vanillawowdb.com/?npc=12056 (Gheddon), the patterns are all roughly 0.1% (which isn't really accurate given that seems to be a rounded figure). However they should be somewhere between 0.6%-2% based on the boss and pattern in question

This is the gheddon drop table link from 1.6:
http://web.archive.org/web/20050829055248/http://wow.allakhazam.com:80/db/mob.html?wmob=1205

Now not all bosses and/or patterns have such nice data and some only have 1.9 as the earliest record on wayback, however on https://wow.gamepedia.com/Molten_Core, the patch changes that could be interpreted to modify the pattern chances all seem to have finished with 1.6.

**Comment by ghost** [comment]
fixed
