### ISSUE TITLE
Maiden's Circle

### ISSUE THREAD

**Issue by Franzz** [Nostralia/Bugtracker#5]
In game: +9 damage
![image](https://user-images.githubusercontent.com/298765/30107442-e23f52d0-9352-11e7-96ef-f23635f0d8e5.png)

11.02.2005: + 10 damage
https://web-beta.archive.org/web/20050211195319/http://wow.allakhazam.com:80/db/item.html?witem=13001

26.05.2006: +18 damage
https://web-beta.archive.org/web/20060526205223/http://wow.allakhazam.com:80/db/item.html?witem=13001

**Comment by ruscur** [comment]
fixed; it's +18 in this patch after all
